src/backend/contacts-rails/config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :lists do 
    member do
      delete 'empty'
    end
  end  

  post 'upload-vcf', to: 'vcf#upload'
  post '/upload-photo', to: 'contacts#upload_photo'
  delete '/delete-photo', to: 'contacts#delete_photo'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

src/backend/contacts-rails/app/models/contact.rb
class Contact < ApplicationRecord
  has_many :list_contacts, dependent: :destroy
  has_many :lists, through: :list_contacts
  
  self.table_name = 'contacts_contact'
    private
  def contact_params
    params.require(:contac).permit(
      full_name: [],
      company: "",
      photo_path: "",
      phone_no: [:cell, :home, :pref],
      email: [:home, :internet]
    )
  end

end

src/backend/contacts-rails/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
    # puts "B4: #{@contact.photo_path}"
    # @contact.photo_path = @contact.photo_path.gsub("/Users/akhileshbitla/Work/projects/contacts/public/", "")
    # puts "A4: #{@contact.photo_path}"
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    list_id = params[:list_id]
  
    if @contact.save
      if list_id.present?
        ListContact.create(list_id: list_id, contact_id: @contact.id)
      end
      render json: @contact
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    if @contact.update(contact_params)
      render json: @contact
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    list_id = params[:list_id]
    if list_id.present?
      ListContact.where(list_id: list_i, contact_id: @contact.id).destroy_all
    end
    if @contact.destroy
      head :no_content
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  def upload_photo
    photo = params[:photo]
    puts "Photo: #{photo}"

    if photo.present?
      file_name = "#{SecureRandom.uuid}_#{photo.original_filename}"
      file_path = Rails.root.join(ENV["PHOTO_STORAGE_PATH"], "photo_storage", file_name)
      puts "file_path: #{file_path}"
      File.open(file_path, 'wb') do |file|
        file.write(photo.read)
      end

      render json: { success: "Photo successfully uploaded", photo_rel_path: "photo_storage/#{file_name}"  }, status: :ok
    else
      render json: { error: 'No photo uploaded' }, status: :unprocessable_entity
    end
  end

  def delete_photo
    file_path = Rails.root.join(ENV["PHOTO_STORAGE_PATH"], params[:photo_path])

    if File.exist?(file_path)
      File.delete(file_path)
      render json: { success: 'Photo successfully deleted' }, status: :ok
    else
      render json: { error: 'File not found' }, status: :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    private
    def contact_params
      params.require(:contact).permit(
        :company,
        :photo_path,
        full_name: [],
        phone_no: [:cell, :home, :pref],
        email: [:home, :internet]
      ).tap do |whitelisted|
        whitelisted[:phone_no] = {
          cell: (params[:contact][:phone_no][:cell]) || [],
          home: (params[:contact][:phone_no][:home]) || [],
          pref: (params[:contact][:phone_no][:pref]) || []
        }
        
        whitelisted[:email] = {
          home: (params[:contact][:email][:home]) || [],
          internet: (params[:contact][:email][:internet]) || []
        }
        
        Rails.logger.debug "Value of list id: #{params[:contact][:full_name]}"
      end
    end

end

src/backend/contacts-rails/app/helpers/contacts_helper.rb
module ContactsHelper
end

src/backend/contacts-rails/app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Full name:</strong>
    <%= contact.full_name %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= contact.company %>
  </p>

  <p>
    <strong>Photo path:</strong>
    <%= contact.photo_path %>
  </p>

  <p>
    <strong>Phone no:</strong>
    <%= contact.phone_no %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

</div>

src/backend/contacts-rails/app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name, "Full Name (separate words with spaces)" %>
    <%= form.text_field :full_name, name:'contact[full_name][]', id: "full_name_input" %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :photo_path %>
    <%= form.text_field :photo_path %>
  </div>

  <div class="field">
    <%= form.label :phone_no, "Phone Numbers" %>
    <div>
      <%= form.label :phone_no_cell, "Cell" %>
      <%= form.text_field :phone_no_cell, value: contact.phone_no['cell'].join(", ") %>
    </div>
    <div>
      <%= form.label :phone_no_home, "Home" %>
      <%= form.text_field :phone_no_home, value: contact.phone_no['home'].join(", ") %>
    </div>
    <div>
      <%= form.label :phone_no_pref, "Preferred" %>
      <%= form.text_field :phone_no_pref, value: contact.phone_no['pref'].join(", ") %>
    </div>
  </div>

  <div class="field">
    <%= form.label :email, "Emails" %>
    <div>
      <%= form.label :email_home, "Home" %>
      <%= form.text_field :email_home, value: contact.email['home'].join(", ") %>
    </div>
    <div>
      <%= form.label :email_internet, "Internet" %>
      <%= form.text_field :email_internet, value: contact.email['internet'].join(", ") %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const form = document.querySelector("form");
    form.addEventListener("actions", function(event) {
      // Process full name input into an array
      const fullNameInput = document.getElementById("full_name_input");
      const fullNameHidden = document.getElementById("full_name_hidden");
      const fullNames = fullNameInput.value.split(" ").map(name => name.trim()).filter(name => name !== "");
      fullNameInput.value = JSON.stringify(fullNames);
    });
  });
</script>

src/backend/contacts-rails/app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

src/backend/contacts-rails/app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

src/backend/contacts-rails/app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

src/backend/contacts-rails/app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>